### ISSUE TITLE
`Model.plot` cannot return anything 😭

### ISSUE THREAD

**Issue by jfthuong** [pyansys/pydpf-core#197]
The function `Model.plot` cannot return any result, unlike its cousin from `pyvista`:
https://docs.pyvista.org/api/plotting/_autosummary/pyvista.plot.html

In particular, we can have 3 types of results:
* `return_img`: for returning a np-array
* `return_cpos`: for returning camera position
* `return_viewer`: for returning a jupyterlab viewer, scene, or display object when plotting with jupyter notebook

We need to replace:

```python
        self.metadata.meshed_region.grid.plot(
            color=color, show_edges=show_edges, **kwargs
        )
```

by 

```python
        return self.metadata.meshed_region.grid.plot(
            color=color, show_edges=show_edges, **kwargs
        )
```

... i.e. adding a `return` 🧙‍♂️

Also, we could a link to Pyvista doc in pydpf doc (https://dpfdocs.pyansys.com/api/ansys.dpf.core.model.html?highlight=plot#ansys.dpf.core.model.Model.plot)

**Comment by PProfizi** [comment]
Hi @jfthuong, I've been working on plotting recently and I came back on your Issue. #253
As far as return_cpos is concerned, it works.
For return_img, there is a weird behavior and especially it does not output anything right now as you can see here https://github.com/pyvista/pyvista/issues/1665. Thus theoretically my modifications will make this available, but once the bug is resolved on the pyvista side.
As for return_viewer, it does work when I try it on Jupyter notebook:
`a = model.plot(notebook=True, return_viewer=True)` will store the viewer and not plot.
`a` will plot.

The plotting functions now all return the result of the `show_figure` method, which when using PyVista is `pyvista.Plotter.show` under the hood.
The main change in #194 is that kwargs are now correctly passed along. So you should be able to use any valid combination.

**Comment by PProfizi** [comment]
See #253
