### ISSUE TITLE
Changing plot title

### ISSUE THREAD

**Issue by pmaroneh** [pyansys/pydpf-core#88]
I create a plot thanks to:
mesh = model.metadata.meshed_region
mesh.plot(my_field)
I'd like to change the title of this plot. I tried using the 'text' argument of the plot function of PyVista (https://docs.pyvista.org/api/plotting/_autosummary/pyvista.plot.html?highlight=mesh%20plot):
mesh.plot(my_field,text='dummy title')
But I get the following error:
![image](https://user-images.githubusercontent.com/76440649/137345330-c581cdaa-0fdc-4015-b051-51a49ea9d991.png)
Am I using this incorrectly? Not sure whether the issue is related to DPF-Core or to PyVista here.
Thanks!

**Comment by natter1** [comment]
I don't think its your fault. `pymapdl`was imroved a lot during the latest releases in refards to plotting (still more work is needed). `pydpf-core`and pydpf-post` on the other hand are still very limited in regards to plotting, and need to be changed. See e.g. [pypdf-post/#36](https://github.com/pyansys/pydpf-post/issues/36). 

You could try to change your plots via pyvista Themes, as described [here](https://docs.pyvista.org/examples/02-plot/themes.html#themes-example). But I think thats also not working for all cases (e.g. I have not tested what happens if you set a title). Or you need to create the pyvista plot yourself from the data you want to plot. Sadly there is no example for this as far as I know (I would like such an example too, as I would like to plot results together with deformed shapes)
